{% set name = "qe-tools" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 289239e981f84bcf2f94b9a4716dd2e59fa68630404311ed2774e4b51b4ca80f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit >=3.4,<4
    - pip
    - python >=3.6
  run:
    - numpy
    - packaging
    - python >=3.6
    - scipy

test:
  imports:
    - qe_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiidateam/qe-tools
  summary: A set of useful tools to manage Quantum ESPRESSO files
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
